fix Scheduler: T1097917
DevExpress/devextreme-react pull request #729
Opened 2022-07-04 08:02 UTC by GoodDayForSurf

2022-07-07 10:51 UTC, dxvladislavvolkov requested changes

2022-07-07 10:51 UTC, dxvladislavvolkov commented on packages/devextreme-react/src/core/dx-template.ts
> +      const onRemoved = (): void => {
Looks like we need add a test to cover this code.

2022-07-07 10:51 UTC, dxvladislavvolkov commented on packages/devextreme-react/src/core/dx-template.ts
> +            onRemoved: onRemoved,
Use shorter syntaxis. Just { onRemoved }

2022-07-08 08:37 UTC, ivanblinov2k17 approved these changes

2022-07-08 10:31 UTC, GoodDayForSurf reviewed
поменял

2022-07-08 10:31 UTC, GoodDayForSurf reviewed
добавил

2022-07-14 18:25 UTC, dxvladislavvolkov approved these changes

2022-07-15 10:40 UTC, merged